FINNHUB_API_KEY = <YOUR_API_HERE>
POLYGON_API_KEY = <YOUR_API_HERE>
AWS_ACCESS_KEY_ID = <YOUR_API_HERE>
AWS_SECRET_ACCESS_KEY = <YOUR_API_HERE>
DISCORD_WEBHOOK = "https://discord.com/api/webhooks/1163710431001595925/NQeCVcKpHqUphR4lk1Tm37w9PIrIl70U9I5V_D9ndY5y-iYZM9qpSUjn8im76dA6etvJ"
